theme: jekyll-theme-cayman
title: An adaptation of Aldus Manutius in His Shop
description: This website is dedicated to understanding the historical context of a print depicting the sixteenth-century printer Aldus Manutius and an adaptation intended as an advertisement for a present-day tech company like Google. 
