theme: jekyll-theme-cayman
title: Aldus Manutius 2019
description: A site dedicated the adaptation of a print depicting the sixteenth-century printer Aldus Manutius for a present-day tech company advertisement. 
