theme: jekyll-theme-cayman
title: An Adaptation of Aldus Manutius in His Shop
description: A site dedicated the adaptation of a print depicting the sixteenth-century printer Aldus Manutius for a present-day tech company advertisement. 
