theme: jekyll-theme-cayman
title: Welcome to the The History of Text Technology's GitHub site!
description: Towards the end of the course, you (students) will make your own site on GitHub and practice writing in markdown, making pull requests, commits, and eventually, this is where create your final projects. 
